### PR TITLE
Added bank management system

### PR DESCRIPTION
**Pull request by Kritika30032002**
Issue:#13 
I have added bank management system. Please look into it. @Rancho2002

### CODE REVIEW

**Review by Rancho2002 — CHANGES_REQUESTED** [review]
Add a readme.md with a demo video describing what your project does after execution.

**Comment by Kritika30032002** [comment]
okay

**Comment by Kritika30032002** [comment]
Issue:#13

@Rancho2002  Through video it is much difficult to understand the execution of this project.

Thus I added readme with steps and functions that can be performed along with text and image.

Let me know if then also you feel that video is must, then I will add it too.

Also add the label of #hacktoberfest to it

**Review by Rancho2002 — APPROVED** [review]
Congrats! You made a successful PR 🥳🥳. Don't forget to give a ⭐.

**Comment by Kritika30032002** [comment]
Already given star

**Pull request merged**
