### PR TITLE
Mini-Voting-system

### PR DESCRIPTION
**Pull request by mrbhatt2348**

### CODE REVIEW

**Comment by Rancho2002** [comment]
Create a readme.md which describes your project

**Review by Rancho2002 — CHANGES_REQUESTED** [review]
Add a readme.md with your directory which describes your project.

**Comment by mrbhatt2348** [comment]
Added it

**Comment by Rancho2002** [comment]
Congrats on making your first PR successfully 🥳

**Comment by mrbhatt2348** [comment]
Pls add hactoberfest tag in it...

**Comment by mrbhatt2348** [comment]
> Congrats on making your first PR successfully 🥳

Thank you 😊

**Review by Rancho2002 — COMMENTED** [review]
✅

**Pull request merged**
