### PR TITLE
Traffic Control Project

### PR DESCRIPTION
**Pull request by go4krishanu**

### CODE REVIEW

**Review by Rancho2002 — CHANGES_REQUESTED** [review]
Inside library management, create a readme file and upload a demo video for better understanding and for the Traffic control, we only accept C projects, so .cpp files are not acceptable.

**Comment by go4krishanu** [comment]
Video Added Kindly merge it. Thanks

**Comment by go4krishanu** [comment]
> Inside library management, create a readme file and upload a demo video for better understanding and for the Traffic control, we only accept C projects, so .cpp files are not acceptable.

Added demo video for  library management,

**Review by Rancho2002 — CHANGES_REQUESTED** [review]
The demo video must inside readme.md, not anywhere else. As well as delete the traffic control if this is not a C project.

**Comment by go4krishanu** [comment]
Updated the Readme.md with the video kindly check and merge it.
Thanks

**Comment by go4krishanu** [comment]
> The demo video must inside readme.md, not anywhere else. As well as delete the traffic control if this is not a C project.

Updated the Readme.md with the video kindly check and merge it.
Thanks

**Review by Rancho2002 — APPROVED** [review]
Congrats on making it to successful PR 🥳🥳. Don't forget to ⭐ this repo.

**Pull request merged**
