### PR TITLE
Pushing My Calendar Project written in C

### PR DESCRIPTION
**Pull request by PrakharSinha-09**
waiting to get merged my first PR...Thankyou!

### CODE REVIEW

**Review by Rancho2002 — CHANGES_REQUESTED** [review]
Add the code inside a directory(name of the directory must be the project name) and create a readme.md with a demo video describing your project.

**Comment by PrakharSinha-09** [comment]
Closing the current PR, opening with new, sorry for the inconvenience!

**Comment by PrakharSinha-09** [comment]
How to add the video to readme file?

**Comment by Rancho2002** [comment]
Hi @PrakharSinha-09 , in the readme.file, you can drag and drop the video directly.

**Pull request closed without merging**
