### PR TITLE
Adds Grep Command Project developed in the C

### PR DESCRIPTION
**Pull request by Sushant-1999**

### CODE REVIEW

**Comment by Sushant-1999** [comment]
@Rancho2002  Please merge the PR I have added grep command project in C language

**Review by Rancho2002 — CHANGES_REQUESTED** [review]
The folder and files are not visible to me, creat a directory named with project name and add the files inside the directory and create PR

**Comment by Sushant-1999** [comment]
@Rancho2002 it is fixed now can you check and merge it again

**Review by Rancho2002 — CHANGES_REQUESTED** [review]
You nailed it @Sushant-1999 . Just one more thing, add a video demo with readme, (just drag and drop the video inside readme.md) and create PR. It will be merged 100%.

**Comment by Sushant-1999** [comment]
ok @Rancho2002

**Comment by Sushant-1999** [comment]
I think screenshots are enough to understand the all command do u want video @Rancho2002  ??

**Comment by Sushant-1999** [comment]
Also usage.c contains all the commands to use @Rancho2002

**Comment by Sushant-1999** [comment]
To run the program i have added makefile. Just type make in the terminal and use all the commands provided in the screenshots that will give all overview of grep command is that sufficient @Rancho2002

**Comment by Sushant-1999** [comment]
READEME.md file also there already in the project. So, overall screenshots, usage.c and README.md these 3 files are sufficient to understand all grep command that are being developed bro @Rancho2002

**Comment by Sushant-1999** [comment]
Have a look and then tell me @Rancho2002

**Comment by Rancho2002** [comment]
Hi @Sushant-1999 when someone visit your code, its hard for that user to go through all the screenshots and other files one by one to understand it. So adding a demo video will increase interest of your project to understand it. Hope you understand.

**Comment by Sushant-1999** [comment]
ok fine I will add tomorrow @Rancho2002

**Comment by Sushant-1999** [comment]
@Rancho2002 should I add drive link having video description of the project ??

**Comment by Rancho2002** [comment]
> @Rancho2002 should I add drive link having video description of the project ??

sure!

**Comment by Sushant-1999** [comment]
@Rancho2002  I have added google drive link for demo video I have tried my best to explain it Please merge the PR it will be accepted in hacktoberfest team right ???

**Review by Rancho2002 — APPROVED** [review]
Congrats on making this PR successfully 🥳🥳. Don't forget to ⭐ the repo.

**Comment by Rancho2002** [comment]
Hi @Sushant-1999 I have merged your PR, but your video file is too large. What is the reason? You can use loom or obs studio to record videos in decent format with less size. So kindly change the video file?

**Comment by Sushant-1999** [comment]
Hi @Rancho2002 I have used vokoscreen for recording. I will try another software and update you.

**Comment by Sushant-1999** [comment]
@Rancho2002  I am using ubuntu linux machine can you please suggest me any good software for ubuntu ??

**Comment by Rancho2002** [comment]
> @Rancho2002 I am using ubuntu linux machine can you please suggest me any good software for ubuntu ??

OBS studio available for every type of OS, you can try it.https://obsproject.com/download

**Comment by Sushant-1999** [comment]
Hi @Rancho2002 , bro your Repo has been excluded for hacktoberfest. It was really good project so I thought it will get PR accept. Its really disappointing.

**Comment by Rancho2002** [comment]
> Hi @Rancho2002 , bro your Repo has been excluded for hacktoberfest. It was really good project so I thought it will get PR accept. Its really disappointing.

yes bro, but why :(

**Comment by Sushant-1999** [comment]
Don't know bro someone might have reported your repo I think. Just do one things send email to hacktoberfest for the same at least you will come to know the reason. Send the mail asap @Rancho2002

**Comment by Rancho2002** [comment]
> Don't know bro someone might have reported your repo I think. Just do one things send email to hacktoberfest for the same at least you will come to know the reason. Send the mail asap @Rancho2002

yes bro, I am asking in hacktoberfest discord server, but they are not answering. Will you join the chat pls ? https://discord.com/channels/720788516837261322/735506302784110652/1029743074848559194

**Pull request merged**
