### PR TITLE
Issued my code about my project in c (Calculator)

### PR DESCRIPTION
**Pull request by Nithin1306**

### CODE REVIEW

**Review by Rancho2002 — CHANGES_REQUESTED** [review]
Hi @Nithin1306 add a video demo, how your projects work in readme section

**Review by Rancho2002 — CHANGES_REQUESTED** [review]
Hi @Nithin1306 you have uploaded video file in wrong format and wrong destination. Follow this steps to create a successful PR: 
Firsty, convert this .webm file to mp4 or other format so that it can be uploaded in readme.md file
Secondly, check the preview whether a video or video link is properly come in your readme file and then create your pull request. and atlast delete the .webm file
HOPE IT HELPS

**Review by Rancho2002 — CHANGES_REQUESTED** [review]
Good to see you have made so far. Now just 'drag and drop' or upload that Calculatorcode.mp4 inside readme.md and delete the calculatorcode.mp4, then create PR.

**Comment by Nithin1306** [comment]
ok done!!

**Comment by Rancho2002** [comment]
Congrats on making this successful PR 🥳🥳. Don't forget to ⭐ this repo.

**Comment by Nithin1306** [comment]
Already stared this repo :)

**Pull request merged**
